main: xyz.acrylicstyle.storageBox.StorageBoxPlugin
name: StorageBox
version: ${version}
api-version: 1.15
author: acrylic-style
depend:
  - Vault
  - packetevents
softdepend:
  - mcMMO
  - MyPet
commands:
  storagebox:
    aliases: ["sb", "storage"]

permissions:
  storagebox.op:
    default: op